In [1]:
import torch
import torch.nn as nn

In [5]:
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features) # wx + b
        out = self.sigmoid(out)

        return out
        

In [6]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features)

tensor([[0.5875],
        [0.5868],
        [0.5080],
        [0.6751],
        [0.6104],
        [0.5748],
        [0.6012],
        [0.5639],
        [0.5565],
        [0.5346]], grad_fn=<SigmoidBackward0>)

In [7]:
model.linear.weight

Parameter containing:
tensor([[-0.1105,  0.1414, -0.4107,  0.0708,  0.4355]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([0.2754], requires_grad=True)

In [11]:
from torchinfo import summary

In [12]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Buliding a complex NN

In [15]:
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):

        out = self.linear1(features) # wx + b
        out = self.relu(out)
        out = self.linear2(out) # wx + b
        out = self.sigmoid(out)
        

        return out
        

In [16]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features)

tensor([[0.5046],
        [0.4758],
        [0.4771],
        [0.4894],
        [0.5019],
        [0.4848],
        [0.4734],
        [0.5095],
        [0.4932],
        [0.5042]], grad_fn=<SigmoidBackward0>)

In [21]:
model.linear2.weight

Parameter containing:
tensor([[-0.5621, -0.2887, -0.4499]], device='cuda:0', requires_grad=True)

In [22]:
model.linear2.bias

Parameter containing:
tensor([0.1866], device='cuda:0', requires_grad=True)

In [19]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequential Container

In [24]:
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
        
    def forward(self, features):

        out = self.network(features)

        return out
        

In [25]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features)

tensor([[0.6273],
        [0.6192],
        [0.5939],
        [0.6442],
        [0.6452],
        [0.5990],
        [0.6501],
        [0.5955],
        [0.6222],
        [0.5967]], grad_fn=<SigmoidBackward0>)