In [1]:
import torch
print(torch.__version__)

2.4.1+cu121


In [4]:
if torch.cuda.is_available():
    print("GPU is avail")
    print(f"using gpu: {torch.cuda.get_device_name(0)}")
else:
    print("using CPU")

GPU is avail
using gpu: NVIDIA GeForce RTX 3050 Laptop GPU


In [8]:
a = torch.empty(2,3)
a

tensor([[-3.5776e-07,  1.3691e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [7]:
type(a)

torch.Tensor

In [9]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.rand(2, 3) # without using seed

tensor([[0.3693, 0.9460, 0.2772],
        [0.0334, 0.7925, 0.3134]])

In [16]:
torch.manual_seed(1000)
torch.rand(2,3)

tensor([[0.3189, 0.6136, 0.4418],
        [0.2580, 0.2724, 0.6261]])

In [18]:
torch.tensor([[1, 2, 3], [4, 56, 7]])

tensor([[ 1,  2,  3],
        [ 4, 56,  7]])

In [20]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [21]:
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [23]:
torch.full((3, 3), 5) # 3x3 tensor filled with every value 5

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [25]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
x.shape

torch.Size([2, 3])

In [28]:
torch.empty_like(x) # same shape diff. values

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Tensor DataTypes

In [32]:
x.dtype

torch.int64

In [33]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [34]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [35]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [37]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.4410, 0.3653, 0.3535],
        [0.5971, 0.3572, 0.4807]])

# Mathematical Ops

In [39]:
x = torch.rand(2,2)
x

tensor([[0.6818, 0.0473],
        [0.4856, 0.0260]])

In [44]:
print(x + 2)
print(x - 2)
print(x * 2)
print(x / 3)
print((x*100) // 2)
print((x*100) % 2)

tensor([[2.6818, 2.0473],
        [2.4856, 2.0260]])
tensor([[-1.3182, -1.9527],
        [-1.5144, -1.9740]])
tensor([[1.3637, 0.0946],
        [0.9713, 0.0521]])
tensor([[0.2273, 0.0158],
        [0.1619, 0.0087]])
tensor([[34.,  2.],
        [24.,  1.]])
tensor([[0.1841, 0.7283],
        [0.5625, 0.6030]])


In [63]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [64]:
a

tensor([[0.2569, 0.1575, 0.0148],
        [0.6573, 0.8463, 0.8787]])

In [65]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[0.8407, 0.4625, 0.4894],
        [0.6801, 1.5143, 1.4340]])
tensor([[-0.3269, -0.1475, -0.4597],
        [ 0.6344,  0.1784,  0.3234]])
tensor([[0.1500, 0.0480, 0.0070],
        [0.0150, 0.5653, 0.4880]])
tensor([[ 0.4400,  0.5163,  0.0313],
        [28.7552,  1.2671,  1.5824]])


In [48]:
torch.abs(a-b) # also there is round, ceil, floor

tensor([[0.6446, 0.3346, 0.2739],
        [0.5793, 0.4216, 0.2144]])

In [50]:
torch.clamp(a*b, min=2, max=3) # below range are set to min, above range are set to max

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [51]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[6, 8, 5],
        [6, 0, 7]])

In [52]:
torch.sum(e)

tensor(32)

In [54]:
print(torch.sum(e, dim=0))
print(torch.sum(e, dim=1))


tensor([12,  8, 12])
tensor([19, 13])


In [78]:
y = torch.rand(2,4)
y.to(torch.float32)

tensor([[0.6447, 0.8081, 0.0081, 0.3580],
        [0.2408, 0.8467, 0.8249, 0.4714]])

In [79]:
torch.mean(y)

tensor(0.5253)

In [80]:
torch.mean(y, dim=1) # same as mediam, max, min, product, std, var, argmax(position of the largest item) , argmin

tensor([0.4547, 0.5959])

In [81]:
# matmul, det, inverse,

In [82]:
# has special functions, log, exp, sqrt, sigmoid, softmax, relu

In [83]:
torch.sigmoid(y)

tensor([[0.6558, 0.6917, 0.5020, 0.5886],
        [0.5599, 0.6999, 0.6953, 0.6157]])

In [84]:
torch.softmax(y, dim=0) #only considers float

tensor([[0.5996, 0.4904, 0.3064, 0.4717],
        [0.4004, 0.5096, 0.6936, 0.5283]])

# Inplace Ops

In [86]:
a.add_(b)

tensor([[0.8407, 0.4625, 0.4894],
        [0.6801, 1.5143, 1.4340]])

In [87]:
b

tensor([[0.5838, 0.3050, 0.4746],
        [0.0229, 0.6680, 0.5553]])

In [88]:
a.relu_()

tensor([[0.8407, 0.4625, 0.4894],
        [0.6801, 1.5143, 1.4340]])

# Copying a Tensor

In [98]:
m = torch.rand(3, 2)
n = torch.rand(3, 2)

In [99]:
m

tensor([[0.4181, 0.7387],
        [0.5685, 0.5926],
        [0.5074, 0.3858]])

In [100]:
n

tensor([[0.0187, 0.4892],
        [0.8931, 0.5635],
        [0.9389, 0.8019]])

In [101]:
n = m.clone()

In [102]:
id(m)

1831021401248

In [103]:
id(n)

1831021297360

# Tensors using GPU

In [114]:
torch.cuda.is_available()

True

In [115]:
device = torch.device('cuda')

In [116]:
x = torch.rand((2,3), device=device)

In [117]:
x

tensor([[0.4943, 0.8782, 0.3201],
        [1.0000, 0.6300, 0.1473]], device='cuda:0')

In [118]:
a = torch.rand(2,3)

In [119]:
b = a.to(device)

In [120]:
b + 5

tensor([[5.2144, 5.6179, 5.6671],
        [5.7510, 5.1432, 5.4122]], device='cuda:0')

In [123]:
if torch.cuda.is_available():
    print("GPU is avail")
    print(f"using gpu: {torch.cuda.get_device_name(0)}")
else:
    print("using CPU")

GPU is avail
using gpu: NVIDIA GeForce RTX 3050 Laptop GPU


In [124]:
torch.cuda.is_available()

True

In [125]:
import time

In [127]:
size = 10000
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(cpu_time)

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
result_cpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(gpu_time)

3.6096837520599365
0.45442986488342285


In [128]:
import numpy as np

In [129]:
c = np.array([1,2,3])

In [130]:
torch.from_numpy(c)

tensor([1, 2, 3], dtype=torch.int32)

In [131]:
x = torch.rand(2, 3)

In [132]:
x.numpy()

array([[0.9948882 , 0.13979489, 0.20726848],
       [0.8662255 , 0.20758301, 0.8804913 ]], dtype=float32)